#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication splitMeshRegions -cellZonesOnly -overwrite

runApplication decomposePar -allRegions

touch post.foam

runParallel $(getApplication)

#------------------------------------------------------------------------------
