#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication splitMeshRegions -cellZonesOnly -overwrite

runApplication decomposePar -allRegions

runApplication mpirun -np 4 chtMultiRegionFoam -parallel

runApplication $(getApplication)

runApplication reconstructPar -allRegions -newTimes

#------------------------------------------------------------------------------
